import Head from 'next/head'
import React from 'react'
import Featured from '../components/Featured'
import ProductList from '../components/ProductList'

export default function Home() {
  return (
    <React.Fragment>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Featured />
      <ProductList/>
    </React.Fragment>
  )
}
